name: clock_checker
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ntp: ^1.0.6  
  intl: ^0.16.1
  url_launcher: ^5.4.5
  timezone: ^0.5.7
  validators: ^2.0.0
  country_icons: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/bigfrog2_cropped.jpg
  - assets/horakhty_avatar.png
  - assets/int_flag.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Italic.ttf
          weight: 700
        - asset: fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: fonts/UbuntuCondensed-Regular.ttf